title:              Vonnish
email:              shinhyuk1001@kaist.ac.kr
description:        Change to Chance!
author:             Shinhyeok Hwang
baseurl:            "/"
url:                "https://vonnish.github.io"

# Social Profiles
twitter_username:   
github_username:    vonnish
facebook_username:  shinhyuk1001  
instagram_username: hkkk.29
linkedin_username:  shinhyeok-hwang-4826611aa

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-170946918-1  # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
